title: gta san andreas mysterys forum
author: dstua mystery man
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  dis is da forum for discussing all gta san andreas mysterys from 
  gta san andreas, a game released by Rockstar Games in 2004 about
  mysterys in the game.

# social links
twitter_username: your-twitter-handle
github_username:  https://github.com/dstua
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
